### ISSUE TITLE
Undo invalid flight while still in flight

### ISSUE THREAD

**Issue by thijsvdc** [sanhozay/PilotLog#19] opened 2021-09-30 12:11 UTC
## Versions

Please complete all of the following:

PilotLog version   :  2.0.0
Java version       :   openjdk 15.0.3 2021-04-20
Flightgear version :  2020.3.8
O/S                :  Mint 20.2
O/S version        :  
Browser            :  FF
Browser version    :  

## Problem Description

As long as #16 is not fixed, is there a way to remove the invalid mark before the flight gets deleted?

**Comment by sanhozay** [comment] 2021-09-30 12:27
No, not really.

Are you able to edit pilotlog.nas with this change?

Near the bottom of the file, change this section:

```
setlistener("sim/speed-up", func(node) {
    if (int(node.getValue()) != 1)
        invalidate("Simulation+speed+was+changed");
}, startup=0, runtime=0);
```

to read as follows:

```
setlistener("sim/speed-up", func(node) {
    if (int(node.getValue()) != 1) {
        # Allow accidental speed up, as long as it is reverted
        # within a short timeframe
        var t = maketimer(5, func {
            if (int(node.getValue()) != 1)
                invalidate("Simulation+speed+was+changed");
        });
        t.singleShot = 1;
        t.start();
    }
}, startup=0, runtime=0);
```

That gives you five seconds to undo any time warp if you press it accidentally. Obviously you can change the number 5 to a longer period if you like.

**Comment by thijsvdc** [comment] 2021-10-04 21:13
Sorry for the delay.
Unfortunately those changes do not seem to work.
I've set the timer to 30s, only time warped for a couple of seconds, but the flight is still invalidated.

Let met know if you need more logs or info.

**Comment by sanhozay** [comment] 2021-10-04 21:19
OK, sorry that didn't work. It looks like it should. I'll try and get my Flightgear up and running and try it. What version are you running?

**Comment by thijsvdc** [comment] 2021-10-08 20:15
Pilotlog 2.0.0 and FG  2020.3.8

**Comment by sanhozay** [comment] 2022-03-03 10:50
I'm closing this one as a duplicate of issue #16. I'll try and fix those Nasal script changes I suggested.

**Closed as completed by sanhozay** 2022-03-03 10:50 UTC
